POST http://localhost:8102/comment/63514d29e8fa0003f32f1e08
Content-Type: application/json
Authorization: Basic 63481082e51d0de7116533d4

{
    "text" : "4 comment looks like 4 comet.",
    "author" : "newtestuser110"
}